services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: learnmate
      POSTGRES_PASSWORD: learnmate
      POSTGRES_DB: learnmate
    volumes:
      - learnmate_pg:/var/lib/postgresql/data

volumes:
  learnmate_pg:
